name: ci

on:
  push:
    branches:
      - "dev-2024"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven ServidorDeDirectorios
      run:
        mvn -f ./ServidorDeDirectorios/pom.xml package -DskipTests
    - name: Build with Maven ServidorDeArchivos
      run:
        mvn -f ./ServidorDeArchivos/pom.xml package -DskipTests
    - name: Build with Maven Gateway
      run:
        mvn -f ./Gateway/pom.xml package -DskipTests
        
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: ServidorDeDirectorios/Dockerfile
           image: "ServidorDeDirectorios"
           cache-to: ...
           cache-from: ...
         - dockerfile: ServidorDeArchivos/Dockerfile
           image: "ServidorDeArchivos"
           cache-to: ...
           cache-from: ...
         - dockerfile: Gateway/Dockerfile
           image: "Gateway"
           cache-to: ...
           cache-from: ...
         - dockerfile: Front/Dockerfile
           image: "Front"
           cache-to: ...
           cache-from: ...
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: ${{ matrix.dockerfile }}
          context: .
          image: : ${{ matrix.image }}
          cache-to: ${{ matrix.cache-to}}
          cache-from: ${{ matrix.cache-from}}
