name: ci

on:
  push:
    branches:
      - "dev-2024"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: LS
      run:
        ls
    - name: Build with Maven ServidorDeDirectorios
      run:
        mvn -f ./ServidorDeDirectorios/pom.xml package -DskipTests
    - name: Build with Maven ServidorDeArchivos
      run:
        mvn -f ./ServidorArchivos/pom.xml package -DskipTests
    - name: Build with Maven Gateway
      run:
        mvn -f ./Gateway/pom.xml package -DskipTests
        
    - name: Publish ServidorArchivos
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/ServidorArchivos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ServidorArchivos
        
    - name: Publish ServidorDeDirectorios
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/ServidorDeDirectorios
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ServidorDeDirectorios
  
