name: ci

on:
  push:
    branches:
      - "dev-2024"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: front.key generationn
      run:
        echo ${{ secrets.PRIVATE_KEY }} | fold -w 64 >> Front/front.key
    - name: password file generation
      run:
        echo ${{ secrets.SSL_PASSWORD }} | fold -w 64 >> Front/password
    - name: LS
      run:
        ls
    - name: Build with Maven ServidorDeDirectorios
      run:
        mvn -f ./ServidorDeDirectorios/pom.xml package -DskipTests
    - name: Build with Maven ServidorDeArchivos
      run:
        mvn -f ./ServidorArchivos/pom.xml package -DskipTests
    - name: Build with Maven Gateway
      run:
        mvn -f ./Gateway/pom.xml package -DskipTests
        
    - name: Publish ServidorArchivos
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/servidor-archivos2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ServidorArchivos
        tags: "latest"
        
    - name: Publish ServidorDeDirectorios
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/servidor-directorios
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ServidorDeDirectorios
        tags: "latest"
        
    - name: Publish Gateway
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/gateway
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: Gateway
        tags: "latest"
        
    - name: Publish Gateway Front
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nicolaslarena/gateway-front
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: Front
        tags: "latest, v1.0.27"
  
